name: shelf_body_parser
description: Shelf 的中间件 用于解析get,post 参数及文件
version: 1.0.7
homepage: https://github.com/928799934/shelf_body_parser
author: lijian <928799934@qq.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mime: ^1.0.0
  shelf: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
