name: shelf_body_parser
description: Shelf 的中间件 用于解析get,post 参数及文件
version: 1.0.6
homepage: https://github.com/928799934/shelf_body_parser
author: lijian <928799934@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  mime: ^0.9.6+3
  shelf: ^0.7.5
  http_parser: ^3.1.3

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
